# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kinectdlg.ui'
#
# Created: Wed Feb 20 01:20:53 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_KinectDialog(object):
    def setupUi(self, KinectDialog):
        KinectDialog.setObjectName(_fromUtf8("KinectDialog"))
        KinectDialog.resize(583, 667)
        self.verticalLayout = QtGui.QVBoxLayout(KinectDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(KinectDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.image_rb = QtGui.QRadioButton(KinectDialog)
        self.image_rb.setObjectName(_fromUtf8("image_rb"))
        self.horizontalLayout.addWidget(self.image_rb)
        self.depth_rb = QtGui.QRadioButton(KinectDialog)
        self.depth_rb.setObjectName(_fromUtf8("depth_rb"))
        self.horizontalLayout.addWidget(self.depth_rb)
        self.detection_rb = QtGui.QRadioButton(KinectDialog)
        self.detection_rb.setObjectName(_fromUtf8("detection_rb"))
        self.horizontalLayout.addWidget(self.detection_rb)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_3 = QtGui.QFrame(KinectDialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(KinectDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.blobs_cb = QtGui.QCheckBox(KinectDialog)
        self.blobs_cb.setObjectName(_fromUtf8("blobs_cb"))
        self.horizontalLayout_2.addWidget(self.blobs_cb)
        self.centroids_cb = QtGui.QCheckBox(KinectDialog)
        self.centroids_cb.setObjectName(_fromUtf8("centroids_cb"))
        self.horizontalLayout_2.addWidget(self.centroids_cb)
        self.grid_cb = QtGui.QCheckBox(KinectDialog)
        self.grid_cb.setObjectName(_fromUtf8("grid_cb"))
        self.horizontalLayout_2.addWidget(self.grid_cb)
        self.boundaries_cb = QtGui.QCheckBox(KinectDialog)
        self.boundaries_cb.setObjectName(_fromUtf8("boundaries_cb"))
        self.horizontalLayout_2.addWidget(self.boundaries_cb)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtGui.QFrame(KinectDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(KinectDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_2 = QtGui.QLabel(KinectDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.min_hslider = QtGui.QSlider(KinectDialog)
        self.min_hslider.setOrientation(QtCore.Qt.Horizontal)
        self.min_hslider.setObjectName(_fromUtf8("min_hslider"))
        self.horizontalLayout_3.addWidget(self.min_hslider)
        self.min_label = QtGui.QLabel(KinectDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_label.sizePolicy().hasHeightForWidth())
        self.min_label.setSizePolicy(sizePolicy)
        self.min_label.setMinimumSize(QtCore.QSize(30, 0))
        self.min_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.min_label.setObjectName(_fromUtf8("min_label"))
        self.horizontalLayout_3.addWidget(self.min_label)
        self.label_3 = QtGui.QLabel(KinectDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.max_hslider = QtGui.QSlider(KinectDialog)
        self.max_hslider.setOrientation(QtCore.Qt.Horizontal)
        self.max_hslider.setObjectName(_fromUtf8("max_hslider"))
        self.horizontalLayout_3.addWidget(self.max_hslider)
        self.max_label = QtGui.QLabel(KinectDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_label.sizePolicy().hasHeightForWidth())
        self.max_label.setSizePolicy(sizePolicy)
        self.max_label.setMinimumSize(QtCore.QSize(30, 0))
        self.max_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max_label.setObjectName(_fromUtf8("max_label"))
        self.horizontalLayout_3.addWidget(self.max_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtGui.QFrame(KinectDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(KinectDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(KinectDialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.server_le = QtGui.QLineEdit(KinectDialog)
        self.server_le.setObjectName(_fromUtf8("server_le"))
        self.horizontalLayout_4.addWidget(self.server_le)
        self.send_osc_cb = QtGui.QCheckBox(KinectDialog)
        self.send_osc_cb.setObjectName(_fromUtf8("send_osc_cb"))
        self.horizontalLayout_4.addWidget(self.send_osc_cb)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_4 = QtGui.QFrame(KinectDialog)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout.addWidget(self.line_4)
        self.image_label = QtGui.QLabel(KinectDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setObjectName(_fromUtf8("image_label"))
        self.verticalLayout.addWidget(self.image_label)
        self.label_2.setBuddy(self.min_hslider)
        self.label_3.setBuddy(self.max_hslider)

        self.retranslateUi(KinectDialog)
        QtCore.QMetaObject.connectSlotsByName(KinectDialog)
        KinectDialog.setTabOrder(self.image_rb, self.depth_rb)
        KinectDialog.setTabOrder(self.depth_rb, self.min_hslider)
        KinectDialog.setTabOrder(self.min_hslider, self.max_hslider)

    def retranslateUi(self, KinectDialog):
        KinectDialog.setWindowTitle(QtGui.QApplication.translate("KinectDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("KinectDialog", "Base image:", None, QtGui.QApplication.UnicodeUTF8))
        self.image_rb.setText(QtGui.QApplication.translate("KinectDialog", "Input image", None, QtGui.QApplication.UnicodeUTF8))
        self.depth_rb.setText(QtGui.QApplication.translate("KinectDialog", "Input depth", None, QtGui.QApplication.UnicodeUTF8))
        self.detection_rb.setText(QtGui.QApplication.translate("KinectDialog", "Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("KinectDialog", "Features:", None, QtGui.QApplication.UnicodeUTF8))
        self.blobs_cb.setText(QtGui.QApplication.translate("KinectDialog", "Blobs", None, QtGui.QApplication.UnicodeUTF8))
        self.centroids_cb.setText(QtGui.QApplication.translate("KinectDialog", "Centroids", None, QtGui.QApplication.UnicodeUTF8))
        self.grid_cb.setText(QtGui.QApplication.translate("KinectDialog", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.boundaries_cb.setText(QtGui.QApplication.translate("KinectDialog", "Boundaries", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("KinectDialog", "Depth filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("KinectDialog", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.min_label.setText(QtGui.QApplication.translate("KinectDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("KinectDialog", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.max_label.setText(QtGui.QApplication.translate("KinectDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("KinectDialog", "OSC:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("KinectDialog", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.send_osc_cb.setText(QtGui.QApplication.translate("KinectDialog", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.image_label.setText(QtGui.QApplication.translate("KinectDialog", "Image", None, QtGui.QApplication.UnicodeUTF8))

